# Generated by Django 5.0.9 on 2024-09-30 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='hashed_password',
        ),
    ]
