# Generated by Django 5.0.9 on 2024-10-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_users_hashed_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='author_id',
        ),
        migrations.AddField(
            model_name='posts',
            name='author_username',
            field=models.CharField(default='ananya', max_length=20),
            preserve_default=False,
        ),
    ]
