# Generated by Django 5.0.9 on 2024-10-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_delete_users_remove_posts_author_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='tags',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
