# Generated by Django 5.0.9 on 2024-10-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_likes_posts_likes_no_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image',
            field=models.FileField(null=True, storage='storages.backends.s3boto3.S3Boto3Storage', upload_to='images/'),
        ),
    ]
